### ISSUE TITLE
Question regarding Http Provider life cycle

### ISSUE THREAD

**Issue by paluh** [WowzaMediaSystems/wse-plugin-referervalidate#1]
Hi,

I'm trying to understand flow of this plugin and I have question regarding initialization of `HttpRefererValidate`.

Could you explain why there is instance [cache as vhost property]( https://github.com/WowzaMediaSystems/wse-plugin-referervalidate/blob/master/src/com/wowza/wms/plugin/HttpRefererValidate.java#L90)? Do you want to force usage of single instance of this provider per vhost?

Could you explain a bit [`onBind` method flow](https://github.com/WowzaMediaSystems/wse-plugin-referervalidate/blob/master/src/com/wowza/wms/plugin/HttpRefererValidate.java#L66)?

Thanks!

**Comment by rogerlittin** [comment]
Hi,

The reason for this workflow is that we only want one HttpProvider instance loaded for the VHost but when there are multiple port numbers defined for a Hostport or the HttpProvider is defined multiple times (for different HostPorts) then there is separate HttpProvider instances loaded up for each port number or HostPort.

The onBind method is the first place where we can access the HttpProvider and check to see if we already have an instance loaded. We store the first one in a vhost property then reference that from any others that are created. At the Application level, we also reference the same property.

This design came from the very early days of Wowza Media Server (WMS 1.x) where a HostPort could only have one network port defined so it would only have one set of HttpProviders. In WMS 2, we added the ability to define multiple network ports per HostPort configuration however the underlying code is still needs to create separate bindings for each of these and so also creates separate HttpProviders.

If you know you won't have separate ports configured or you aren't referencing something specifically in the HttpProvider instance then you probably don't need to implement this type of workflow but in this case, the HttpProvider is storing data about each of the referrers that connects so there must only be one instance for the VHost.  We can't use a singleton because there could be multiple VHosts which would have separate HttpProviders by design.

I hope this helps,

Roger.

**Comment by paluh** [comment]
Wow! Your response really clarifies what is going on here. Thanks a lot Roger!
